name: map_picker_flutter
description: Get the address quickly and easily from Google Map in Web, Desktop and Mobile.
version: 1.1.0+2
homepage: https://github.com/Bestfastfire/map_picker_flutter

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  rxdart: ^0.27.3
  latlng: ^0.1.0
  dio: ^4.0.6
  map: ^1.0.0

  flutter:
    sdk: flutter
  cached_network_image: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
